---
language: ruby
cache: bundler
script: "bundle exec rspec --color --format documentation spec/unit"
notifications:
  email: false
sudo: false
rvm:
  - "2.4.1"
  - "2.1.9"
  - "2.0.0"
  - "1.9.3"
  - "jruby-19mode"
jdk:
  - oraclejdk8
